# Generated by Django 6.0.3 on 2026-03-26 13:45

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='profile_pics/default.jpg', force_format=None, keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='profile_pics/'),
        ),
    ]
